### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Denwen12** [RyanG73/DFS_Baseball#1]
im trying to use your program but i run into this sometimes

Traceback (most recent call last):
  File "DFS_0.0.1.py", line 41, in <module>
    master['Pos'] = np.where(master['Pos'].isna(),'P',master['Pos'])
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/lib/python3/dist-packages/pandas/core/generic.py", line 2491, in _get_item_cache
    values = self._data.get(item)
  File "/usr/lib/python3/dist-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Pos'

**Comment by RyanG73** [comment]
That particular script is archived. If you are looking for the current script to scrape data and optimize a single lineup, run DFS_Safe_1.0.0.py.

I have several active strands on this project and it's not yet too organized, hence no ReadMe, but if there are other questions or ideas let me know.

**Comment by Denwen12** [comment]
do you have a way to run multi lineups?

**Comment by Denwen12** [comment]
also can you spit out a csv with all player peojections?

**Comment by RyanG73** [comment]
> do you have a way to run multi lineups?

DFS_MonteCarlo_1.0.1.py is designed to run as many simulations as you could want, but it is currently just the equivalent of a random distribution of outcomes. there's no actual math behind it.

**Comment by Denwen12** [comment]
also can i remove all the files in data and start for today on each fanduel slates players list

**Comment by RyanG73** [comment]
> also can you spit out a csv with all player projections?

when the script outputs the optimized lineup the "slate" tab in the excel workbook will have all the projections for every eligible player in the FanDuel contest of your choice. 

If you truly wanted projection for _every_ player then you could push the "master" dataframe to excel after it is done scraping

**Comment by Denwen12** [comment]
it seems your program does good lineups since i won on fanduels each slate

**Comment by RyanG73** [comment]
> also can i remove all the files in data and start for today on each fanduel slates players list

yes, old lineups and player files are virtually worthless beyond post-analysis. when you pick the fanduel contest you want to play in you can download the eligible player list to csv and drop that in.

**Comment by Denwen12** [comment]
@RyanG73 , also its not printing out the excel on my system, what should i check into, i work on a debian system

**Comment by Denwen12** [comment]
i just tryed to run it now and i got

DFS_Safe_1.0.0.py:63: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  slate['Name'] = slate['Name'].str.replace(' Jr.', '')
data cleaned
problem defined
constraints in place
Traceback (most recent call last):
  File "DFS_Safe_1.0.0.py", line 89, in <module>
    catchers = catchers['Name'].to_list()
  File "/usr/lib/python3/dist-packages/pandas/core/generic.py", line 4378, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'to_list'

**Comment by RyanG73** [comment]
i will have a look a bit later

**Comment by Denwen12** [comment]
i tryed to run it with the 940pm slate players list

**Comment by Denwen12** [comment]
does the players list gotta have the hitting order in cause fanduel doesnt post that early?

**Comment by Denwen12** [comment]
and thx for your quick response

**Comment by Denwen12** [comment]
im not sure if series is referring to CIN @ KC (2)
maybe a double header

**Comment by Denwen12** [comment]
still working on this now i get

File "DFS_Safe_1.0.0.py", line 53, in <module>
    master['Pos'] = np.where(master['Pos'].isna(),'P',master['Pos'])
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3081, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'isna'

**Comment by RyanG73** [comment]
Huge potential issue is that based on your error message it appears you are using python 2.7. You will need to upgrade to 3+ (easy to download) I do have a couple small updates that I’ll push tonight so you can test run before the 9pm slate

**Comment by Denwen12** [comment]
okay i do have 3.7 so ill try on that

**Comment by Denwen12** [comment]
i did some upgrades to my packages now i got 
Lineup Status: Optimal
The optimal lineup consists of
----------------------------------------------------------------------------------------------------
              Name  Pos       Team       Game  FanDuel   Salary
0   Anthony Rendon   3B     Angels   LAA @ SF    13.06   3900.0
1   Cody Bellinger   OF    Dodgers  LAD @ SEA    14.74   4000.0
2     Corey Seager   SS    Dodgers  LAD @ SEA    12.28   3800.0
3     Joc Pederson   OF    Dodgers  LAD @ SEA    11.55   2600.0
4      Julio Urias    P    Dodgers  LAD @ SEA    28.64   7900.0
5       Matt Olson   1B  Athletics  ARI @ OAK    12.38   3600.0
6       Mike Trout   OF     Angels   LAA @ SF    14.19   4600.0
7      Sean Murphy    C  Athletics  ARI @ OAK     9.57   2200.0
8  Tommy La Stella   2B     Angels   LAA @ SF    11.20   2300.0
9              NaN  NaN        NaN        NaN   127.61  34900.0
--- 5.247 minutes ---

Thanks cant wait to see what you did tonight

**Comment by Denwen12** [comment]
what will DFS_MonteCarlo_1.0.1.py do

**Comment by Denwen12** [comment]
i found a problem in this lineup for main slate
0    Adam Duvall   OF     Braves  WSH @ ATL    12.72   2400.0
1     Adam Eaton   OF  Nationals  WSH @ ATL    12.51   2600.0
2   Alex Bregman   3B     Astros  HOU @ COL    17.64   4300.0
3   Austin Riley   OF     Braves  WSH @ ATL    13.20   2400.0
4  Carlos Correa   SS     Astros  HOU @ COL    14.94   3600.0
5   Jacob deGrom    P       Mets  NYM @ MIA    38.97  10700.0
6    Jose Altuve   2B     Astros  HOU @ COL    16.17   3900.0
7   Mitch Garver    C      Twins  MIL @ MIN    13.15   2500.0
8   Taylor Jones   1B     Astros  HOU @ COL    12.93   2500.0
9            NaN  NaN        NaN        NaN   152.23  34900.0

austin riley is a 3B on fanduel so im not sure how youd fix errors like this so these would be valid lineups to enter and because we already picked a 1B and a C to be used in C/1B and util slot, no way to enter two 3B guys

**Comment by RyanG73** [comment]
great! feel free to upload your fork. im about to push some updates that should streamline the code on file paths and clarify what is what. plus i intend to update the readme this weekend. Do note that one thing im still working on that this code doesnt account for is "team stacking." If you are familiar with DFS you will have heard this before, but basically it means correlated outcomes between players on the same team because if one player hits a home run the other players will get more points as they have a chance of being on base. Good news is the lineup generated for your timeslot seems to have stacked the dodgers by default, which makes it more optimal. 


in regard to your second comment. I had to update the code at one point because i was mistakenly using the position of the player listed on fangraphs, and not fanduel. i have since switched this. when the new code is pushed you should be able to re-run with it being solved.

**Comment by Denwen12** [comment]
Great i do know quite of bit about fantasy so if you dont mind i like to help here with testing

**Comment by RyanG73** [comment]
for sure, happy to have you. the joy of open source. I just pushed the new DFS_Safe_1.0.0.py file and it should be a bit easier this time around and fix the positions issue. be sure to delete the excel output from your previous run, that way the script re-downloads the player positions properly.

**Comment by Denwen12** [comment]
going to test it now

**Comment by Denwen12** [comment]
made a perfect lineup for the 810pm slate
0   Christian Yelich   OF    Brewers  MIL @ MIN    11.55   4100.0
1  Edwin Encarnacion   1B  White Sox  DET @ CWS    12.71   2500.0
2       Eloy Jimenez   OF  White Sox  DET @ CWS    11.81   3300.0
3    Jonathan Schoop   2B     Tigers  DET @ CWS    11.06   2800.0
4       Mitch Garver    C      Twins  MIL @ MIN    13.15   2500.0
5        Nelson Cruz   OF      Twins  MIL @ MIN    13.53   4200.0
6          Rich Hill    P      Twins  MIL @ MIN    28.90   7400.0
7       Tim Anderson   SS  White Sox  DET @ CWS    11.60   3400.0
8       Yoan Moncada   3B  White Sox  DET @ CWS    12.06   3600.0
9                NaN  NaN        NaN        NaN   126.37  33800.0
--- 5.152 minutes ---

**Comment by Denwen12** [comment]
i download the 840pm player list and replaced the file i had in data now i get this error
Traceback (most recent call last):
  File "DFS_Safe_1.0.0.py", line 17, in <module>
    fd = pd.read_csv(csv[0])
IndexError: list index out of range

any idea?

**Comment by RyanG73** [comment]
> i download the 840pm player list and replaced the file i had in data now i get this error
> Traceback (most recent call last):
> File "DFS_Safe_1.0.0.py", line 17, in
> fd = pd.read_csv(csv[0])
> IndexError: list index out of range
> 
> any idea?

if you are changing your slate, you probably need to take the previous slate and previous output and dump it into an archive folder.

**Comment by Denwen12** [comment]
okay, Thanks for being patient with me while i learn this

**Comment by RyanG73** [comment]
no problem. the project has very little organization right now so i can totally understand why its not clear

**Comment by Denwen12** [comment]
same with my server here at home this laptop is a new deb install so i gotta find a way to fix my system time 
![Uploading 15978850963597361836892426689530.jpg…]()

**Comment by Denwen12** [comment]
the lineups we got last night were terrible lmao, but that doesn't matter, but anyways thats what testing is about winning some and losing some till we got something good, so what does analysis_today.py do for us

**Comment by Denwen12** [comment]
or can you explain what your other programs do?

**Comment by Denwen12** [comment]
if we ran monte carlo to have it create tons of lineups, Anyway we can have that save lineups like this in a csv?

```
P | C/1B | 2B | 3B | SS | OF | OF | OF | UTIL | Budget | FPPG
48556-79224 | 48556-52175 | 48556-52176 | 48556-6312 | 48556-21705 | 48556-13864 | 48556-79159 | 48556-12933 | 48556-17198 | 34700 | 133.11
48556-79224 | 48556-80485 | 48556-52176 | 48556-6312 | 48556-38412 | 48556-79175 | 48556-79159 | 48556-12933 | 48556-17198 | 34900 | 132.77
48556-79224 | 48556-80485 | 48556-52176 | 48556-6312 | 48556-38412 | 48556-82440 | 48556-79159 | 48556-12933 | 48556-17198 | 34800 | 132.64
48556-52166 | 48556-52175 | 48556-52176 | 48556-6312 | 48556-21705 | 48556-13864 | 48556-79159 | 48556-12933 | 48556-17198 | 34500 | 130.94
48556-52166 | 48556-52175 | 48556-52176 | 48556-6312 | 48556-21705 | 48556-79175 | 48556-79159 | 48556-12933 | 48556-17198 | 34900 | 130.88
```

**Comment by Denwen12** [comment]
everytime it ran a new simulation add that line to csv?
